name: k6 Performance Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install k6 (modern key installation)
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common curl
          # Download and save k6 GPG key
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          # Add k6 repository using signed-by
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Create results directory
        run: mkdir -p results

      - name: Run Load Test
        run: k6 run src/scenarios/load.test.js --out json=results/summary.json

      - name: Run Realistic Flow Test
        run: k6 run src/scenarios/realistic-flow.test.js

      - name: Upload Performance Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: results/
